# Generated by Django 5.0.6 on 2024-09-29 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Chatbot', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='register',
            new_name='UserRegistration',
        ),
    ]
